### ISSUE TITLE
Kanban Board Project

### ISSUE THREAD

**Issue by AyoubM490** [AyoubMs/api-capstone-project#21]
This is a copy of the JavaScript Group Capstone Project [Kanban board template].
All tasks have been added for a team of 2 members.
Roles have been assigned for each task on the board.
- Project Link: https://github.com/AyoubMs/api-capstone-project/projects/1
Team: 
- Ayoub Chahir
- Mahmoud Rizk

**Comment by rustam-tolipov** [comment]
## HELLO team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
